const places=window.PLACES;
const categoryMeta={"Zwembad & water":{"icon":"💦","color":"#2d9cff"},"Attractiepark":{"icon":"🎢","color":"#ff4f70"},"Dierentuin & dieren":{"icon":"🦁","color":"#28b86b"},"Binnenspeeltuin":{"icon":"🛝","color":"#ffad2f"},"Museum & ontdekken":{"icon":"🔎","color":"#9a66ff"},"Speelpark & actief":{"icon":"🧗","color":"#f15bb5"},"Kasteel & natuur":{"icon":"🏰","color":"#12b7a6"}};
const fallbackOrigin={lat:51.696614298792,lon:5.9429794410288,label:"Urlingsestraat 7, 5441 XJ Oeffelt"};
let origin={...fallbackOrigin};
const state={search:'',country:'all',setting:'all',sort:'distance',category:'all'};
let map,homeMarker,ring60,ring150,markerLayer;
const markers=new Map();
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function hav(lat1,lon1,lat2,lon2){const R=6371.0088,p1=lat1*Math.PI/180,p2=lat2*Math.PI/180,dp=(lat2-lat1)*Math.PI/180,dl=(lon2-lon1)*Math.PI/180;const a=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
function recalcDistances(){places.forEach(p=>p.distance=Math.round(hav(origin.lat,origin.lon,p.lat,p.lon)*10)/10)}
function routeUrl(p){return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin.label)}&destination=${p.lat},${p.lon}`}
function filtered(){let list=places.filter(p=>{const q=state.search.trim().toLowerCase();const hit=!q||[p.name,p.city,p.category,p.note].join(' ').toLowerCase().includes(q);return hit&&(state.country==='all'||p.country===state.country)&&(state.setting==='all'||p.setting===state.setting)&&(state.category==='all'||p.category===state.category)});list.sort((a,b)=>state.sort==='name'?a.name.localeCompare(b.name,'nl'):a.distance-b.distance);return list}
function initMap(){map=L.map('map',{zoomControl:true,scrollWheelZoom:true}).setView([origin.lat,origin.lon],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);drawOrigin();}
function drawOrigin(){if(homeMarker)map.removeLayer(homeMarker);if(ring60)map.removeLayer(ring60);if(ring150)map.removeLayer(ring150);const homeIcon=L.divIcon({className:'',html:'<div class="home-marker">🏠</div>',iconSize:[46,46],iconAnchor:[23,23]});homeMarker=L.marker([origin.lat,origin.lon],{icon:homeIcon,zIndexOffset:2000}).addTo(map).bindPopup(`<div class="popup"><h3>Startpunt</h3><p>${esc(origin.label)}</p></div>`);ring60=L.circle([origin.lat,origin.lon],{radius:60000,color:'#3c68ff',weight:2,fillColor:'#3c68ff',fillOpacity:.035,dashArray:'7 7'}).addTo(map).bindTooltip('Nederland: zoekgebied tot 60 km');ring150=L.circle([origin.lat,origin.lon],{radius:150000,color:'#8d66ff',weight:2,fillColor:'#8d66ff',fillOpacity:.018,dashArray:'9 8'}).addTo(map).bindTooltip('Duitsland: zoekgebied tot 150 km');}
function markerIcon(p){const m=categoryMeta[p.category]||{color:'#64748b',icon:'📍'};return L.divIcon({className:'',html:`<div class="magic-marker" style="background:${m.color}"><span>${m.icon}</span></div>`,iconSize:[38,38],iconAnchor:[19,35],popupAnchor:[0,-34]})}
function popupHtml(p){const m=categoryMeta[p.category]||{icon:'📍'};return `<div class="popup"><h3>${esc(p.name)}</h3><p>${m.icon} ${esc(p.category)} · ${esc(p.city)}</p><p><strong>${p.distance.toFixed(1)} km</strong> hemelsbreed vanaf Urlingsestraat 7</p>${p.status?`<p style="color:#a54b00"><strong>${esc(p.status)}</strong></p>`:''}<div class="popup-links"><a href="${esc(p.website)}" target="_blank" rel="noopener">Website</a><a href="${esc(routeUrl(p))}" target="_blank" rel="noopener">Route</a></div></div>`}
function renderMarkers(list){markerLayer.clearLayers();markers.clear();list.forEach(p=>{const marker=L.marker([p.lat,p.lon],{icon:markerIcon(p)}).bindPopup(popupHtml(p));marker.addTo(markerLayer);markers.set(p.name,marker)})}
function renderCategories(){const cats=[...new Set(places.map(p=>p.category))];$('categoryRow').innerHTML=`<button class="cat-btn ${state.category==='all'?'active':''}" data-cat="all" style="${state.category==='all'?'background:#173b88':''}">✨ Alles</button>`+cats.map(cat=>{const m=categoryMeta[cat];return `<button class="cat-btn ${state.category===cat?'active':''}" data-cat="${esc(cat)}" style="${state.category===cat?`background:${m.color}`:''}">${m.icon} ${esc(cat)}</button>`}).join('');document.querySelectorAll('.cat-btn').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;update()})}
function renderResults(list){$('resultCount').textContent=`${list.length} locatie${list.length===1?'':'s'} gevonden`;$('results').innerHTML=list.slice(0,60).map(p=>{const m=categoryMeta[p.category]||{color:'#64748b',icon:'📍'};return `<article class="result" data-name="${esc(p.name)}"><div class="result-title"><div class="result-icon" style="background:${m.color}">${m.icon}</div><div><h3>${esc(p.name)}</h3><small>${esc(p.city)} · ${p.distance.toFixed(1)} km</small></div></div><div class="result-meta"><span class="mini">${esc(p.category)}</span><span class="mini">${esc(p.setting)}</span><span class="mini">${p.country==='NL'?'🇳🇱':'🇩🇪'}</span></div></article>`}).join('')||'<div class="no-results">Geen locaties gevonden.</div>';document.querySelectorAll('.result').forEach(el=>el.onclick=()=>{const marker=markers.get(el.dataset.name);if(marker){const p=places.find(x=>x.name===el.dataset.name);map.setView([p.lat,p.lon],12,{animate:true});marker.openPopup();document.getElementById('map').scrollIntoView({behavior:'smooth',block:'center'})}})}
function fallbackSvg(p){const m=categoryMeta[p.category]||{color:'#64748b',icon:'📍'};const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='900' height='560'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='${m.color}'/><stop offset='1' stop-color='#173b88'/></linearGradient></defs><rect width='100%' height='100%' fill='url(#g)'/><circle cx='170' cy='120' r='95' fill='white' opacity='.13'/><circle cx='760' cy='470' r='140' fill='white' opacity='.1'/><text x='450' y='265' font-size='120' text-anchor='middle'>${m.icon}</text><text x='450' y='360' font-family='Arial' font-size='34' fill='white' text-anchor='middle'>${esc(p.name)}</text></svg>`;return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function renderCards(list){$('cards').innerHTML=list.map(p=>{const m=categoryMeta[p.category]||{color:'#64748b',icon:'📍'};return `<article class="place-card"><div class="photo"><img src="${esc(p.image)}" alt="Beeld van ${esc(p.name)}" loading="lazy" data-fallback="${esc(fallbackSvg(p))}"><div class="photo-badge" style="background:${m.color}">${m.icon} ${esc(p.category)}</div><div class="photo-title"><strong>${esc(p.name)}</strong><span>${esc(p.city)} · ${p.distance.toFixed(1)} km vanaf Oeffelt</span></div></div><div class="card-body"><div class="pills"><span class="pill">${p.country==='NL'?'🇳🇱 Nederland':'🇩🇪 Duitsland'}</span><span class="pill">${esc(p.setting)}</span><span class="pill">${p.distance.toFixed(1)} km</span></div><p class="description">${esc(p.note||'')}</p>${p.status?`<div class="warning">${esc(p.status)}</div>`:''}<div class="actions"><a class="btn primary" href="${esc(p.website)}" target="_blank" rel="noopener">Website</a><a class="btn" href="${esc(routeUrl(p))}" target="_blank" rel="noopener">Route</a><button class="btn show-map" data-name="${esc(p.name)}">Op kaart</button></div></div></article>`}).join('')||'<div class="no-results">Geen locaties gevonden.</div>';document.querySelectorAll('.photo img').forEach(img=>img.onerror=()=>{if(img.dataset.fallback&&img.src!==img.dataset.fallback)img.src=img.dataset.fallback});document.querySelectorAll('.show-map').forEach(btn=>btn.onclick=()=>{const p=places.find(x=>x.name===btn.dataset.name);const marker=markers.get(btn.dataset.name);if(p&&marker){map.setView([p.lat,p.lon],12);marker.openPopup();document.getElementById('map').scrollIntoView({behavior:'smooth',block:'center'})}})}
function update(){const list=filtered();renderCategories();renderMarkers(list);renderResults(list);renderCards(list);$('totalStat').textContent=`${places.length} locaties`;}
async function refineOrigin(){try{const url='https://api.pdok.nl/bzk/locatieserver/search/v3_1/free?q='+encodeURIComponent('Urlingsestraat 7 5441 XJ Oeffelt')+'&fq=type:adres&rows=1';const res=await fetch(url);if(!res.ok)throw new Error('PDOK');const data=await res.json();const doc=data?.response?.docs?.[0];const wkt=doc?.centroide_ll||doc?.centroide_rd;if(doc?.centroide_ll){const match=doc.centroide_ll.match(/POINT\(([-\d.]+)\s+([-\d.]+)\)/);if(match){origin={lon:+match[1],lat:+match[2],label:doc.weergavenaam||fallbackOrigin.label};recalcDistances();drawOrigin();update();$('originStatus').textContent='Startpunt gecontroleerd via BAG/PDOK: '+origin.label+'. Afstanden zijn hemelsbreed.';}}}catch(e){$('originStatus').textContent='Startpunt: Urlingsestraat 7, 5441 XJ Oeffelt. Afstanden zijn hemelsbreed berekend op basis van het postcode-/adrespunt.';}}
$('search').addEventListener('input',e=>{state.search=e.target.value;update()});$('country').addEventListener('change',e=>{state.country=e.target.value;update()});$('setting').addEventListener('change',e=>{state.setting=e.target.value;update()});$('sort').addEventListener('change',e=>{state.sort=e.target.value;update()});
recalcDistances();initMap();update();refineOrigin();