const $=id=>document.getElementById(id);
const S={peer:null,conn:null,role:null,room:null,localName:"",names:["Speler 1","Speler 2"],scores:[0,0],wins:[0,0],rounds:10,diff:"normal",order:[],round:0,currentIndex:null,endAt:0,active:false,submitted:[false,false],timer:null,connected:false,nextTimer:null};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(id).classList.add('on')}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function initials(n){return n.replace(/\b(fc|cf|sc|sv|united|city)\b/gi,'').trim().split(/\s+/).slice(0,3).map(x=>x[0]).join('').toUpperCase()||'FC'}
function randomRoom(){return 'cr-'+Math.random().toString(36).slice(2,8)}
function inviteUrl(room){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',room);return u.toString()}
function setNetwork(t){$('networkStatus').textContent='ONLINE DUEL SYSTEM // '+t.toUpperCase()}
function errorHome(t){$('homeError').style.display='block';$('homeError').textContent=t;setNetwork('fout')}
function clearError(){$('homeError').style.display='none';$('homeError').textContent=''}
function destroyConnection(){clearInterval(S.timer);clearTimeout(S.nextTimer);try{S.conn&&S.conn.close()}catch(e){}try{S.peer&&S.peer.destroy()}catch(e){}S.peer=null;S.conn=null;S.connected=false;S.active=false}
function setupPeerErrors(peer){peer.on('error',e=>{console.error(e);if(e.type==='unavailable-id'&&S.role==='host'){errorHome('Deze kamercode bestond toevallig al. Maak opnieuw een kamer.');show('home')}else{errorHome('De online verbinding kon niet worden opgebouwd. Controleer je internetverbinding en probeer opnieuw.');if(!document.querySelector('#game.on'))show('home')}})}
function createRoom(){clearError();if(typeof Peer==='undefined'){errorHome('De online spelmodule kon niet worden geladen. Ververs de pagina.');return}destroyConnection();S.role='host';S.localName=$('hostName').value.trim()||'Manager 1';S.names=[S.localName,'Tegenstander'];S.rounds=+$('roundCount').value;S.diff=$('difficulty').value;S.room=randomRoom();S.peer=new Peer(S.room);setupPeerErrors(S.peer);setNetwork('kamer maken');S.peer.on('open',id=>{S.room=id;$('roomCode').textContent=id.toUpperCase();$('inviteLink').value=inviteUrl(id);$('lobbyP1').textContent=S.localName;$('lobbyP2').textContent='Wachten…';$('lobbyS1').textContent='Verbonden';$('lobbyS2').textContent='Nog niet verbonden';$('hostShareBlock').style.display='block';$('lobbyWaiting').style.display='flex';$('startMatchBtn').style.display='inline-block';$('startMatchBtn').disabled=true;show('lobby');setNetwork('wachten op vriend')});S.peer.on('connection',conn=>{if(S.conn&&S.conn.open){conn.close();return}S.conn=conn;wireConnection(conn)})}
function openManualJoin(){const code=$('manualRoom').value.trim().toLowerCase();if(!code){errorHome('Vul eerst de kamercode in.');return}showJoin(code)}
function showJoin(code){clearError();S.room=code.toLowerCase();$('joinCode').textContent=S.room.toUpperCase();$('hostForm').style.display='none';$('joinForm').style.display='grid';$('homePanelTitle').textContent='Deelnemen aan online duel'}
function cancelJoin(){history.replaceState({},'',location.pathname);$('joinForm').style.display='none';$('hostForm').style.display='grid';$('homePanelTitle').textContent='Maak of open een kamer';clearError()}
function joinRoom(){clearError();if(typeof Peer==='undefined'){errorHome('De online spelmodule kon niet worden geladen. Ververs de pagina.');return}destroyConnection();S.role='guest';S.localName=$('guestName').value.trim()||'Manager 2';setNetwork('verbinden');S.peer=new Peer();setupPeerErrors(S.peer);S.peer.on('open',()=>{S.conn=S.peer.connect(S.room,{reliable:true,metadata:{name:S.localName}});wireConnection(S.conn)})}
function wireConnection(conn){conn.on('open',()=>{S.connected=true;setNetwork('verbonden');if(S.role==='guest'){send({type:'join',name:S.localName});$('roomCode').textContent=S.room.toUpperCase();$('hostShareBlock').style.display='none';$('lobbyWaiting').style.display='flex';$('lobbyWaiting').innerHTML='<span class="dot"></span><span>Verbonden. Wachten tot de organisator start…</span>';$('startMatchBtn').style.display='none';$('lobbyP1').textContent='Organisator';$('lobbyP2').textContent=S.localName;$('lobbyS1').textContent='Verbonden';$('lobbyS2').textContent='Verbonden';show('lobby')}});conn.on('data',data=>S.role==='host'?hostReceive(data):guestReceive(data));conn.on('close',()=>connectionLost());conn.on('error',()=>connectionLost())}
function send(data){if(S.conn&&S.conn.open)S.conn.send(data)}
function hostReceive(d){if(!d||!d.type)return;if(d.type==='join'){S.names=[S.localName,String(d.name||'Vriend').slice(0,18)];$('lobbyP2').textContent=S.names[1];$('lobbyS2').textContent='Verbonden';$('lobbyWaiting').style.display='none';$('startMatchBtn').disabled=false;send({type:'welcome',names:S.names,rounds:S.rounds,diff:S.diff});setNetwork('beide spelers klaar')}else if(d.type==='guess'){hostJudge(1,d.answer)}}
function guestReceive(d){if(!d||!d.type)return;if(d.type==='welcome'){S.names=d.names;S.rounds=d.rounds;S.diff=d.diff;$('lobbyP1').textContent=S.names[0];$('lobbyP2').textContent=S.names[1]}else if(d.type==='start'){S.names=d.names;S.scores=d.scores;S.wins=d.wins;show('game');paintScores();log('De online wedstrijd is gestart.')}else if(d.type==='round'){receiveRound(d)}else if(d.type==='guessStatus'){applyGuessStatus(d.player,d.text)}else if(d.type==='result'){receiveResult(d)}else if(d.type==='end'){receiveEnd(d)}else if(d.type==='notice'){setMessage(d.text,d.kind||'')}}
function hostStartMatch(){if(S.role!=='host'||!S.connected)return;S.scores=[0,0];S.wins=[0,0];S.round=0;S.order=shuffle([...PLAYERS.keys()]).slice(0,S.rounds);send({type:'start',names:S.names,scores:S.scores,wins:S.wins});show('game');paintScores();log('De online wedstrijd is gestart.');setTimeout(hostStartRound,600)}
function hostStartRound(){S.currentIndex=S.order[S.round];S.active=true;S.submitted=[false,false];S.endAt=Date.now()+30000;const p=PLAYERS[S.currentIndex];const packet={type:'round',round:S.round,total:S.rounds,diff:S.diff,clubs:p.clubs,nation:p.nation,position:p.position,endAt:S.endAt,names:S.names,scores:S.scores,wins:S.wins};send(packet);receiveRound(packet);clearTimeout(S.nextTimer);S.nextTimer=setTimeout(()=>{if(S.active)hostFinishRound(null,'De tijd was voorbij. Niemand verdiende punten.')},30500)}
function receiveRound(d){S.round=d.round;S.rounds=d.total;S.diff=d.diff;S.endAt=d.endAt;S.active=true;S.submitted=[false,false];S.names=d.names;S.scores=d.scores;S.wins=d.wins;paintScores();$('roundLabel').textContent=`${S.round+1} / ${S.rounds}`;$('roundProgress').style.width=((S.round+1)/S.rounds*100)+'%';drawCareer(d.clubs,d.diff);drawClues(d);resetGuessStates();$('answerInput').value='';$('answerInput').disabled=false;$('answerBtn').disabled=false;setMessage('Je hebt één poging. Denk goed na voor je indient.','');startClock();show('game');setTimeout(()=>$('answerInput').focus(),150)}
function drawClues(d){$('clueBar').innerHTML='';if(d.diff==='easy'){chip('Nationaliteit: '+d.nation);chip('Positie: '+d.position);chip(d.clubs.length+' clubstappen')}else if(d.diff==='normal'){chip('Nationaliteit: '+d.nation);chip(d.clubs.length+' clubstappen')}else{chip('Legend-modus');chip(d.clubs.length+' clubstappen')}}
function chip(t){const e=document.createElement('div');e.className='chip';e.textContent=t;$('clueBar').append(e)}
function drawCareer(clubs,diff){$('career').innerHTML='';clubs.forEach((c,i)=>{const step=document.createElement('div');step.className='step';const card=document.createElement('div');card.className='club';const wrap=document.createElement('div');wrap.className='logowrap';wrap.innerHTML=`<div class="crest">${initials(c.name)}</div>`;const img=document.createElement('img');img.className='logo';img.alt='Logo '+c.name;img.onload=()=>img.classList.add('loaded');img.onerror=()=>img.remove();img.src=`https://www.google.com/s2/favicons?domain_url=https://${c.domain}&sz=128`;wrap.append(img);const nm=document.createElement('div');nm.className='clubname'+(diff==='easy'?'':' blur');nm.textContent=c.name;card.append(wrap,nm);step.append(card);if(i<clubs.length-1){const a=document.createElement('div');a.className='arrow';a.textContent='›';step.append(a)}$('career').append(step)})}
function submitGuess(){if(!S.active)return;const ans=$('answerInput').value.trim();if(!ans){setMessage('Vul eerst een spelersnaam in.','bad');return}const me=S.role==='host'?0:1;if(S.submitted[me])return;$('answerInput').disabled=true;$('answerBtn').disabled=true;const card=$('guessState'+me);card.className='guessstate done';card.querySelector('span').textContent='Antwoord ingediend';if(S.role==='host')hostJudge(0,ans);else{S.submitted[me]=true;send({type:'guess',answer:ans})}}
function hostJudge(player,answer){if(!S.active||S.submitted[player])return;S.submitted[player]=true;const p=PLAYERS[S.currentIndex];const n=norm(answer);const correct=[p.name,...p.a].some(x=>norm(x)===n);if(correct){const left=Math.max(0,Math.ceil((S.endAt-Date.now())/1000));const pts=100+left*2;S.scores[player]+=pts;S.wins[player]++;hostFinishRound(player,`${S.names[player]} was het snelst en verdient ${pts} punten.`)}else{const text='Fout antwoord — uitgeschakeld voor deze ronde';applyGuessStatus(player,text);send({type:'guessStatus',player,text});if(player===0)setMessage('Je antwoord was fout. Je vriend kan nog scoren.','bad');if(S.submitted[0]&&S.submitted[1])hostFinishRound(null,'Beide antwoorden waren fout. Geen punten in deze ronde.')}}
function hostFinishRound(winner,text){if(!S.active)return;S.active=false;clearTimeout(S.nextTimer);const answer=PLAYERS[S.currentIndex].name;const packet={type:'result',answer,text,winner,scores:S.scores,wins:S.wins};send(packet);receiveResult(packet);S.nextTimer=setTimeout(()=>{S.round++;if(S.round>=S.rounds){const end={type:'end',names:S.names,scores:S.scores,wins:S.wins};send(end);receiveEnd(end)}else hostStartRound()},4500)}
function receiveResult(d){S.active=false;S.scores=d.scores;S.wins=d.wins;clearInterval(S.timer);paintScores();$('answerInput').disabled=true;$('answerBtn').disabled=true;$('resultAnswer').textContent=d.answer;$('resultText').textContent=d.text;$('resultOverlay').classList.add('show');log(d.text);setTimeout(()=>$('resultOverlay').classList.remove('show'),4200)}
function receiveEnd(d){S.names=d.names;S.scores=d.scores;S.wins=d.wins;clearInterval(S.timer);$('resultOverlay').classList.remove('show');const a=S.scores[0],b=S.scores[1];let title,sub;if(a===b){title='Gelijkspel';sub='Geen winnaar. Dit duel vraagt om een revanche.'}else{const w=a>b?0:1;title=S.names[w];sub=Math.abs(a-b)>=250?'Een overtuigende overwinning op voetbalgeheugen.':'Een spannend duel waarin één clubroute het verschil maakte.'}$('winnerText').innerHTML='<span>'+escapeHtml(title)+'</span>';$('winnerSub').textContent=sub;for(let i=0;i<2;i++){$('finalName'+i).textContent=S.names[i];$('finalScore'+i).textContent=S.scores[i]}show('end');setNetwork('wedstrijd afgelopen')}
function startClock(){clearInterval(S.timer);const tick=()=>{const sec=Math.max(0,Math.ceil((S.endAt-Date.now())/1000));$('timer').textContent=sec;$('timer').className='timer'+(sec<=5?' danger':sec<=10?' warn':'');if(sec<=0)clearInterval(S.timer)};tick();S.timer=setInterval(tick,250)}
function resetGuessStates(){for(let i=0;i<2;i++){S.submitted[i]=false;$('guessName'+i).textContent=S.names[i];const e=$('guessState'+i);e.className='guessstate';e.querySelector('span').textContent='Denkt na…'}}
function applyGuessStatus(player,text){S.submitted[player]=true;const e=$('guessState'+player);e.className='guessstate done';e.querySelector('span').textContent=text}
function paintScores(){for(let i=0;i<2;i++){$('scoreName'+i).textContent=S.names[i];$('score'+i).textContent=S.scores[i];$('correct'+i).textContent=S.wins[i]+' rondes gewonnen';$('scoreCard'+i).classList.toggle('me',(S.role==='host'?0:1)===i);$('guessName'+i).textContent=S.names[i]}}
function setMessage(t,kind){$('message').textContent=t;$('message').className='msg'+(kind?' '+kind:'')}
function log(t){const d=document.createElement('div');d.textContent=t;$('gameLog').prepend(d)}
function copyInvite(){navigator.clipboard?.writeText($('inviteLink').value).then(()=>{const old=$('lobbyWaiting').innerHTML;$('lobbyWaiting').style.display='flex';$('lobbyWaiting').innerHTML='<span>Link gekopieerd. Plak hem in WhatsApp.</span>';setTimeout(()=>{$('lobbyWaiting').innerHTML=old},1800)}).catch(()=>{$('inviteLink').select();document.execCommand('copy')})}
async function shareInvite(){const data={title:'Clubroute voetbalduel',text:`Speel Clubroute tegen mij. Kamercode: ${S.room.toUpperCase()}`,url:$('inviteLink').value};if(navigator.share){try{await navigator.share(data)}catch(e){}}else copyInvite()}
function connectionLost(){if(!S.connected)return;S.connected=false;clearInterval(S.timer);setNetwork('verbinding verbroken');alert('De verbinding met je vriend is verbroken. Open de uitnodigingslink opnieuw en maak een nieuwe kamer.');returnHome()}
function leaveRoom(){if(confirm('Wil je het online duel verlaten?'))returnHome()}
function returnHome(){destroyConnection();history.replaceState({},'',location.pathname);$('joinForm').style.display='none';$('hostForm').style.display='grid';$('homePanelTitle').textContent='Maak of open een kamer';$('gameLog').innerHTML='';show('home');setNetwork('ready');clearError()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('answerInput').addEventListener('keydown',e=>{if(e.key==='Enter')submitGuess()});$('playerNames').innerHTML=PLAYERS.map(p=>`<option value="${p.name}"></option>`).join('');
window.addEventListener('beforeunload',()=>destroyConnection());
const invited=new URLSearchParams(location.search).get('room');if(invited)showJoin(invited);
